// /robots.txt — generated by the App Router at build/request time.
// The middleware matcher explicitly excludes .txt/.xml so crawlers hit this
// route directly (no locale rewrite) — see middleware.ts config.
export default function robots() {
  // Read per-call (not module scope) so the base URL follows the deployment.
  const SITE = process.env.NEXT_PUBLIC_APP_URL || "https://www.abumarketplace.shop";
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          // Seller/admin dashboards & auth flows
          "/api/",
          "/admin/",
          "/store/",
          "/sign-in",
          "/sign-up",
          // Account/app pages (localized under /<locale>/…)
          "/account",
          "/orders",
          "/wishlist",
          "/verify-email",
          "/cart",
          "/wallet",
          "/*/account",
          "/*/orders",
          "/*/wishlist",
          "/*/verify-email",
          "/*/cart",
          "/*/wallet",
          "/*/create-store",
          "/*/loading",
        ],
      },
    ],
    sitemap: `${SITE}/sitemap.xml`,
    host: SITE,
  };
}
