// ─── Blue-collar services directory (static seed data) ─────────────────────
// This powers the "For Hire" marketplace section until workers can be
// onboarded through the self-listing flow (which notifies support by email).
// The canonical hourly rate is USD (CurrencyAmount converts it for display).

export const serviceCategories = [
  {
    id: "home",
    labelKey: "services.categories.home",
    trades: ["Plumber", "Electrician", "Carpenter", "Painter", "Cleaner", "Tiler"],
  },
  {
    id: "repair",
    labelKey: "services.categories.repair",
    trades: ["Auto Mechanic", "AC Technician", "Phone & Laptop Repair", "Generator Repair", "Appliance Repair"],
  },
  {
    id: "personal",
    labelKey: "services.categories.personal",
    trades: ["Tailor", "Barber", "Hairstylist", "Makeup Artist", "Caterer"],
  },
];

export const allTrades = serviceCategories.flatMap((cat) => cat.trades);

export const serviceWorkers = [
  // ── Home services ──
  {
    id: "svc_1",
    name: "Ibrahim Sesay",
    trade: "Plumber",
    category: "home",
    location: "Freetown",
    experienceYears: 12,
    rating: 4.9,
    jobsCompleted: 340,
    hourlyRate: 8,
    bio: "Licensed plumber specialising in pipe repairs, bathroom fittings, and water heater installation. Same-day service across Freetown.",
    tags: ["Pipe repairs", "Bathroom fittings", "Water heaters"],
    available: true,
  },
  {
    id: "svc_2",
    name: "Mohamed Koroma",
    trade: "Electrician",
    category: "home",
    location: "Freetown",
    experienceYears: 9,
    rating: 4.8,
    jobsCompleted: 260,
    hourlyRate: 7,
    bio: "Certified electrician for wiring, lighting, breaker boxes, and general home electrical repairs. Safety checks included.",
    tags: ["Wiring", "Lighting", "Breaker boxes"],
    available: true,
  },
  {
    id: "svc_3",
    name: "Josephine Bangura",
    trade: "Carpenter",
    category: "home",
    location: "Waterloo",
    experienceYears: 15,
    rating: 4.9,
    jobsCompleted: 410,
    hourlyRate: 6,
    bio: "Custom furniture, doors, kitchen cabinets, and home repairs. Quality woodwork with on-time delivery.",
    tags: ["Custom furniture", "Cabinets", "Doors"],
    available: false,
  },
  {
    id: "svc_4",
    name: "Abdul Kamara",
    trade: "Painter",
    category: "home",
    location: "Freetown",
    experienceYears: 7,
    rating: 4.7,
    jobsCompleted: 190,
    hourlyRate: 5,
    bio: "Interior and exterior painting, wall finishing, and decorative textures. Clean work, fair pricing, and your paint or ours.",
    tags: ["Interior & exterior", "Wall finishing", "Decorative textures"],
    available: true,
  },
  {
    id: "svc_5",
    name: "Fatmata Conteh",
    trade: "Cleaner",
    category: "home",
    location: "Freetown",
    experienceYears: 6,
    rating: 4.8,
    jobsCompleted: 220,
    hourlyRate: 4,
    bio: "Deep cleaning for homes and offices — kitchens, bathrooms, floors, and windows. Eco-friendly products on request.",
    tags: ["Deep cleaning", "Homes & offices", "Eco-friendly"],
    available: true,
  },
  {
    id: "svc_6",
    name: "Sorie Turay",
    trade: "Tiler",
    category: "home",
    location: "Lumley",
    experienceYears: 10,
    rating: 4.8,
    jobsCompleted: 150,
    hourlyRate: 7,
    bio: "Floor and wall tiling for bathrooms, kitchens, and patios. Neat spacing, durable finishes, and free estimates.",
    tags: ["Floor tiling", "Wall tiling", "Bathrooms & kitchens"],
    available: true,
  },

  // ── Repair & maintenance ──
  {
    id: "svc_7",
    name: "Daniel Cole",
    trade: "Auto Mechanic",
    category: "repair",
    location: "Freetown",
    experienceYears: 14,
    rating: 4.9,
    jobsCompleted: 520,
    hourlyRate: 9,
    bio: "Engine diagnostics, brake repairs, oil changes, and general vehicle maintenance. Mobile service available for breakdowns.",
    tags: ["Engine diagnostics", "Brakes", "Mobile breakdown service"],
    available: true,
  },
  {
    id: "svc_8",
    name: "Alhaji Fofanah",
    trade: "AC Technician",
    category: "repair",
    location: "Freetown",
    experienceYears: 8,
    rating: 4.7,
    jobsCompleted: 310,
    hourlyRate: 8,
    bio: "Air conditioning installation, gas refills, servicing, and repairs for homes and offices. Fast response in hot season.",
    tags: ["Installation", "Gas refills", "Servicing & repairs"],
    available: true,
  },
  {
    id: "svc_9",
    name: "Salamatu Jalloh",
    trade: "Phone & Laptop Repair",
    category: "repair",
    location: "Freetown",
    experienceYears: 5,
    rating: 4.6,
    jobsCompleted: 480,
    hourlyRate: 6,
    bio: "Screen replacements, battery swaps, software fixes, and laptop servicing. Most repairs done the same day.",
    tags: ["Screen replacement", "Batteries", "Software & hardware"],
    available: true,
  },
  {
    id: "svc_10",
    name: "Yusuf Mansaray",
    trade: "Generator Repair",
    category: "repair",
    location: "Wellington",
    experienceYears: 11,
    rating: 4.8,
    jobsCompleted: 290,
    hourlyRate: 8,
    bio: "Generator servicing, engine overhauls, fuel system repair, and starting trouble diagnostics. On-site visits available.",
    tags: ["Servicing", "Engine overhauls", "Starting trouble"],
    available: false,
  },
  {
    id: "svc_11",
    name: "Mariama Bah",
    trade: "Appliance Repair",
    category: "repair",
    location: "Freetown",
    experienceYears: 6,
    rating: 4.7,
    jobsCompleted: 180,
    hourlyRate: 6,
    bio: "Repairs for fridges, freezers, washing machines, and cookers. Honest quotes before any work begins.",
    tags: ["Fridges", "Washing machines", "Cookers"],
    available: true,
  },

  // ── Personal services ──
  {
    id: "svc_12",
    name: "Mariatu Kargbo",
    trade: "Tailor",
    category: "personal",
    location: "Freetown",
    experienceYears: 13,
    rating: 4.9,
    jobsCompleted: 600,
    hourlyRate: 5,
    bio: "Custom tailoring for men and women — suits, gowns, and traditional African wear. Fittings done in my atelier or on site.",
    tags: ["Suits & gowns", "African wear", "Custom fittings"],
    available: true,
  },
  {
    id: "svc_13",
    name: "Ishmael Macauley",
    trade: "Barber",
    category: "personal",
    location: "Freetown",
    experienceYears: 8,
    rating: 4.8,
    jobsCompleted: 1500,
    hourlyRate: 3,
    bio: "Professional cuts, fades, beard grooming, and home/event barber service. Sharp lines every time.",
    tags: ["Fades", "Beard grooming", "Home & event service"],
    available: true,
  },
  {
    id: "svc_14",
    name: "Aminata Sesay",
    trade: "Hairstylist",
    category: "personal",
    location: "Freetown",
    experienceYears: 9,
    rating: 4.9,
    jobsCompleted: 900,
    hourlyRate: 4,
    bio: "Braids, weaves, natural hair care, and event styling. Bridal and party packages available with full team.",
    tags: ["Braids & weaves", "Natural hair", "Bridal styling"],
    available: true,
  },
  {
    id: "svc_15",
    name: "Haja Koroma",
    trade: "Makeup Artist",
    category: "personal",
    location: "Freetown",
    experienceYears: 7,
    rating: 4.8,
    jobsCompleted: 350,
    hourlyRate: 6,
    bio: "Bridal, party, and editorial makeup. Long-lasting looks with professional products. Available for on-location bookings.",
    tags: ["Bridal", "Party looks", "On-location"],
    available: true,
  },
  {
    id: "svc_16",
    name: "Momoh Kanu",
    trade: "Caterer",
    category: "personal",
    location: "Freetown",
    experienceYears: 10,
    rating: 4.7,
    jobsCompleted: 210,
    hourlyRate: 10,
    bio: "Event catering, traditional dishes, and buffet services for weddings, corporate events, and home gatherings.",
    tags: ["Event catering", "Traditional dishes", "Buffets"],
    available: false,
  },
];

